# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4beb047a961ee838d99d0ea8fa40bbe8be9d4db3ed8bcaef09c5ae5bff5f237e019f1cb406d2980bde8a638d7936b8996e8f8f3ec7f5abd1c01d9095aa42801

test:
  secret_key_base: 987329eb3dd76216910ba36166b629f310e49616c87c1bc52480209766274332eee18f28170156e89c39fa81540509a31e17ce147162897ea1df2aaedbf506f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
